project_id = "zdrwzwcaakxkrrlgygbp"

[functions.fire-webhook]
verify_jwt = false

[functions.reset-student-password]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.create-public-sale]
verify_jwt = false
